config/routes.rb
Rails.application.routes.draw do

  root 'workouts#index'

  resources :workouts do
  	resources :exercises
  end

end

app/models/exercise.rb
class Exercise < ActiveRecord::Base
  belongs_to :workout
end

app/models/workout.rb
class Workout < ActiveRecord::Base
	has_many :exercises , dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController

	before_action :find_exercise , only: [:update , :destroy]

	def create
		@workout = Workout.find(params[:workout_id])
		@exercise = @workout.exercises.create(exercise_params)
		redirect_to workout_path(@workout)	
	end

	def edit
		@workout = Workout.find(params[:workout_id])
		@exercise = Exercise.find(params[:id])
	end

	def update
		@workout = Workout.find(params[:workout_id])
		if @exercise.update(exercise_params)
			redirect_to @workout
		else 
			render 'edit'
		end
	end

	def destroy
		@workout = Workout.find(params[:workout_id])
		@exercise.destroy
		redirect_to @workout
	end


	private

	def exercise_params
		params.require(:exercise).permit(:name,:sets,:reps)
	end

	def find_exercise
		@exercise = Exercise.find(params[:id])
	end

end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController

	before_action :find_workout , only: [:show , :edit , :update , :destroy]

	def index
		@workouts = Workout.all.order("created_at DESC")
	end

	def show 
		
	end

	def new
		@workout = Workout.new
	end

	def create
		@workout = Workout.new(workout_params)
		if @workout.save
			redirect_to @workout
		else
			render 'new'
		end
	end

	def edit 

	end

	def update
		if @workout.update(workout_params)
			redirect_to @workout
		else 
			render 'edit'
		end
	end

	def destroy
		@workout.destroy
		redirect_to root_path
	end

	private

	def workout_params
		params.require(:workout).permit( :date , :workout , :mood , :length )
	end

	def find_workout
		@workout = Workout.find(params[:id])
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/exercises_helper.rb
module ExercisesHelper
end

app/helpers/workouts_helper.rb
module WorkoutsHelper
end

app/views/exercises/_exercise.html.erb
<div class="col-lg-6 col-lg-offset-3 col-md-6 col-md-offset-3 col-sm-6 col-sm-offset-3 col-xs-12">

<div class="tcenter">
	<p><%= exercise.name %></p>
	<p><%= exercise.sets %></p>
	<p><%= exercise.reps %></p>
</div>

</div>

app/views/exercises/_form.html.erb
<div class="row">
	<div class="col-lg-6 col-lg-offset-3 col-md-6 col-md-offset-3 col-sm-6 col-sm-offset-3 col-xs-6 col-xs-offset-3">

		<%= simple_form_for([@workout , @workout.exercises.build]) do |f| %>

			<% if @workout.errors.any? %>
		    	<div id="error_explanation">
		      		<h2><%= pluralize(@exercise.errors.count, "error") %> prohibited this todo_list from being saved:</h2>

		      		<ul>
		      			<% @exercise.errors.full_messages.each do |message| %>
		        			<li><%= message %></li>
		      			<% end %>
		      		</ul>
		    	</div>
		  	<% end %>

		  	<%= f.input :name , placeholder: "Name" , class: "form-control" %>
		  	<%= f.input :sets , placeholder: "Number of Sets" , class: "form-control" %>
		  	<%= f.input :reps , placeholder: "Repetitions" , class: "form-control" %>

		  	<%= f.submit class: "btn btn-success form-control" %>

		<% end %>

	</div>
</div>

app/views/exercises/edit.html.erb
<div class="row">
<div class="col-lg-6 col-lg-offset-3 col-md-6 col-md-offset-3 col-sm-6 col-sm-offset-3 col-xs-12">

<h1 class="tcenter">Editing <%= @exercise.name %></h1>

<%= simple_form_for([@workout , @exercise]) do |f| %>

	<% if @workout.errors.any? %>
    	<div id="error_explanation">
      		<h2><%= pluralize(@exercise.errors.count, "error") %> prohibited this todo_list from being saved:</h2>

      		<ul>
      			<% @exercise.errors.full_messages.each do |message| %>
        			<li><%= message %></li>
      			<% end %>
      		</ul>
    	</div>
  	<% end %>

  	<%= f.input :name , placeholder: "Name" , class: "form-control" %>
  	<%= f.input :sets , placeholder: "Number of Sets" , class: "form-control" %>
  	<%= f.input :reps , placeholder: "Repetitions" , class: "form-control" %>

  	<%= f.submit class: "btn btn-success form-control" %>
		
<% end %>

</div>
</div>

app/views/layouts/_navigation.html.erb
<div class="row">
  <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">

    <nav class ="navbar navbar-default">

      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#toggle-links-main">
          <span class="sr-only">Toggle Navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "Workout Log App" , root_path , class: "navbar-brand" %>
      </div>

      <!--Collect Navbar Dropdown Links-->
      <div class="collapse navbar-collapse" id="toggle-links-main">

        <ul class="nav navbar-nav navbar-right">            
              
          <li><%= link_to "New Workout" , new_workout_path %></li>

          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Dropdown<span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <li><a href="#">1</a></li>
              <li><a href="#">2</a></li>
              <li><a href="#">3</a></li>
              <li class="divider"></li>
              <li><a href="#">4</a></li>
              <li class="divider"></li>
              <li><a href="#">5</a></li>
            </ul>
          </li>

        </ul>

      </div>

    </nav>

    <% flash.each do |name,msg| %>
      <%= content_tag(:div,msg, class: "alert alert-info") %>
    <% end %>

  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workout Log App</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
</head>

  <body>

    <div id="main-container" class="container">
      
      <%= render 'layouts/navigation' %>
      
      <%= yield %>
        
    </div>

  </body>

</html>

app/views/workouts/_form.html.erb
<div class="row">
	<div class="col-lg-6 col-lg-offset-3 col-md-6 col-md-offset-3 col-sm-6 col-sm-offset-3 col-xs-12">

		<%= simple_form_for @workout do |f| %>

			<% if @workout.errors.any? %>
		    	<div id="error_explanation">
		      		<h2><%= pluralize(@workout.errors.count, "error") %> prohibited this todo_list from being saved:</h2>

		      		<ul>
		      			<% @workout.errors.full_messages.each do |message| %>
		        			<li><%= message %></li>
		      			<% end %>
		      		</ul>
		    	</div>
		  	<% end %>

		  	<%= f.input :date , placeholder: "Date" %>
		  	
		  	<%= f.input :workout , placeholder: "Which Muscle Group?" , class: "form-control" %>
		  	<%= f.input :mood , placeholder: "Your Mood?" , class: "form-control" %>
		  	<%= f.input :length , placeholder: "How long did it last?" , class: "form-control" %>

		  	<%= f.submit class: "btn btn-success form-control" %>

		<% end %>

	</div>
</div>

app/views/workouts/edit.html.erb
<h1 class="tcenter">Editing <%= @workout.date %></h1>

<%= render 'form' %>

app/views/workouts/index.html.erb
<div class="row">
<div class="col-lg-6 col-lg-offset-3 col-md-6 col-md-offset-3 col-sm-6 col-sm-offset-3 col-xs-12">
	
	<h1 class="tcenter">Logged Workouts for #{user}</h1><br>

	<div class="tcenter">
	<% @workouts.each do |workout| %>
		<% date = workout.date.day.ordinalize %>
		<% string =  workout.date.strftime("%A, %B #{date}")%>

		<p><%= link_to "#{string}" , workout %></p>
		<p><%= workout.workout %></p>

	<% end %>
	</div>

</div>
</div>

app/views/workouts/new.html.erb
<h1 class="tcenter">New Workout</h1>

<%= render 'form' %>

app/views/workouts/show.html.erb
<div class="row">
	<div class="col-lg-6 col-lg-offset-3 col-md-6 col-md-offset-3 col-sm-6 col-sm-offset-3 col-xs-12">
	
		<div class="tcenter">
			<% date = @workout.date.day.ordinalize %>
			<h1 class="tcenter"><%= @workout.date.strftime("%A, %B #{date}") %></h1>
			<h4 class="tcenter"><%= @workout.workout %></h4>

			<%= link_to "Edit" , edit_workout_path(@workout) %> | 
			<%= link_to "Delete" , workout_path(@workout) , method: :delete , data: {confirm: "Are You Sure?"} %>
		</div>

		<br>

		<div class="tcenter exercises">
			
			<% if @workout.exercises.present? %>
				<h2>Exercises</h2>
				<% count = 1 %>
				<table class="table table-bordered">
					<thead>
						<th>#</th>
						<th>Name</th>
						<th>Sets</th>
						<th>Reps</th>
					</thead>
				
					<tbody>
						<% @workout.exercises.each do |exercise| %>
						<tr class="touchDelete">
							<th><%= count %></th>
							<td><%= link_to exercise.name , edit_workout_exercise_path(@workout,exercise) %></td>
							<td><%= exercise.sets %></td>
							<td><%= exercise.reps %></td>
							<td style="display:none;" class="displayDelete" ><%= link_to "Delete" , workout_exercise_path(@workout,exercise) , method: :delete , data: {confirm: "Are You Sure?"}  %>
							</td>
						</tr>
						<% count += 1 %>
						<% end %>
					</tbody>
				</table>
			<% end %>
			
			
			<h3>Add an Exercise</h3>
			<%= render "exercises/form" %>
		</div>

	</div>
</div>


<script>
$('document').ready(function() {
	$('.touchDelete').on("touchmove" , function(e) {
		$('.displayDelete').toggle("fast");
	});
	$('.touchDelete').on("click" , function(e) {
		$('.displayDelete').toggle("fast");
	});
});
</script>